-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity neural_network_neural_network_Pipeline_VITIS_LOOP_56_1_layer1_weights_11_RAM_2P_BRAM_1R1W is 
    generic(
             DataWidth     : integer := 11; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of neural_network_neural_network_Pipeline_VITIS_LOOP_56_1_layer1_weights_11_RAM_2P_BRAM_1R1W is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000000000", 1 => "11111001000", 2 => "00000000000", 3 => "00000000000", 
    4 => "00001101010", 5 => "00000000110", 6 => "11111010011", 7 => "00000000000", 
    8 => "00011000110", 9 => "00000000000", 10 => "00000000000", 11 => "00000000000", 
    12 => "00000000000", 13 => "11010111010", 14 => "11111001101", 15 => "00000000000", 
    16 => "10110011101", 17 => "00000000000", 18 => "00000000000", 19 => "00000000000", 
    20 => "00000000000", 21 => "11001011010", 22 => "00000000000", 23 => "00000000000", 
    24 => "00000000000", 25 => "00000000000", 26 => "00000000000", 27 => "00000001000", 
    28 => "00000000000", 29 => "00010110110", 30 => "00000000000", 31 => "00000000000", 
    32 => "00000000000", 33 => "00000000000", 34 => "00000000000", 35 => "00000000000", 
    36 => "00000000000", 37 => "00000011001", 38 => "00000000000", 39 => "00000000000", 
    40 => "00000000000", 41 => "11001001010", 42 => "00000000000", 43 => "00100101101", 
    44 => "00000000000", 45 => "00000000000", 46 => "00000000000", 47 => "00000000000", 
    48 => "00000000000", 49 => "00000000000", 50 => "00000000000", 51 => "00000000000", 
    52 => "00000000000", 53 => "01010010110", 54 => "00000000000", 55 => "00000000000", 
    56 => "00000000000", 57 => "00000000000", 58 => "00000000000", 59 => "00000000000", 
    60 => "00000000000", 61 => "00000000000", 62 => "11111100011", 63 => "00000000000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block_rom"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

