set SynModuleInfo {
  {SRCNAME neural_network_Pipeline_VITIS_LOOP_42_1 MODELNAME neural_network_Pipeline_VITIS_LOOP_42_1 RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1
    SUBMODULES {
      {MODELNAME neural_network_mul_10s_16s_24_1_1 RTLNAME neural_network_mul_10s_16s_24_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_mac_muladd_9s_16s_24ns_24_4_1 RTLNAME neural_network_mac_muladd_9s_16s_24ns_24_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_mac_muladd_10s_16s_24ns_24_4_1 RTLNAME neural_network_mac_muladd_10s_16s_24ns_24_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_mac_muladd_11s_16s_24ns_24_4_1 RTLNAME neural_network_mac_muladd_11s_16s_24ns_24_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_mac_muladd_12s_16s_24ns_24_4_1 RTLNAME neural_network_mac_muladd_12s_16s_24ns_24_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_0_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_1_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_2_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_2_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_3_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_3_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_4_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_4_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_5_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_5_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_6_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_6_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_7_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_7_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_8_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_8_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_9_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_9_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_10_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_10_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_11_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_11_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_12_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_12_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_13_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_13_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_14_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_14_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_15_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_15_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_16_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_16_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_17_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_weights_17_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_bias_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_42_1_layer1_bias_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_flow_control_loop_pipe_sequential_init RTLNAME neural_network_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME neural_network_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME neural_network_Pipeline_VITIS_LOOP_52_3 MODELNAME neural_network_Pipeline_VITIS_LOOP_52_3 RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3
    SUBMODULES {
      {MODELNAME neural_network_mul_11s_15ns_24_1_1 RTLNAME neural_network_mul_11s_15ns_24_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_mac_muladd_11s_15ns_24ns_24_4_1 RTLNAME neural_network_mac_muladd_11s_15ns_24ns_24_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_mac_muladd_10s_15ns_24ns_24_4_1 RTLNAME neural_network_mac_muladd_10s_15ns_24ns_24_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_mac_muladd_12s_15ns_24ns_24_4_1 RTLNAME neural_network_mac_muladd_12s_15ns_24ns_24_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_0_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_1_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_2_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_2_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_3_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_3_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_4_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_4_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_5_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_5_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_6_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_6_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_7_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_7_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_8_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_8_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_9_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_9_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_10_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_10_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_11_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_11_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_12_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_12_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_13_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_13_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_14_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_14_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_15_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_15_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_16_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_16_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_17_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_17_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_18_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_18_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_19_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_weights_19_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_bias_ROM_AUTO_1R RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_52_3_layer2_bias_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME neural_network_Pipeline_VITIS_LOOP_19_1 MODELNAME neural_network_Pipeline_VITIS_LOOP_19_1 RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_19_1}
  {SRCNAME {exp<17, 9>} MODELNAME exp_17_9_s RTLNAME neural_network_exp_17_9_s
    SUBMODULES {
      {MODELNAME neural_network_mul_25ns_25ns_50_1_1 RTLNAME neural_network_mul_25ns_25ns_50_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_mul_25ns_18ns_43_1_1 RTLNAME neural_network_mul_25ns_18ns_43_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_exp_17_9_s_f_x_lsb_table_ROM_AUTO_1R RTLNAME neural_network_exp_17_9_s_f_x_lsb_table_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_exp_17_9_s_exp_x_msb_2_m_1_table_ROM_AUTO_1R RTLNAME neural_network_exp_17_9_s_exp_x_msb_2_m_1_table_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_exp_17_9_s_exp_x_msb_1_table_ROM_AUTO_1R RTLNAME neural_network_exp_17_9_s_exp_x_msb_1_table_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME neural_network_Pipeline_VITIS_LOOP_23_2 MODELNAME neural_network_Pipeline_VITIS_LOOP_23_2 RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_23_2}
  {SRCNAME neural_network_Pipeline_VITIS_LOOP_28_3 MODELNAME neural_network_Pipeline_VITIS_LOOP_28_3 RTLNAME neural_network_neural_network_Pipeline_VITIS_LOOP_28_3
    SUBMODULES {
      {MODELNAME neural_network_sdiv_24ns_16s_16_28_1 RTLNAME neural_network_sdiv_24ns_16s_16_28_1 BINDTYPE op TYPE sdiv IMPL auto LATENCY 27 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME neural_network MODELNAME neural_network RTLNAME neural_network IS_TOP 1
    SUBMODULES {
      {MODELNAME neural_network_layer1_output_RAM_AUTO_1R1W RTLNAME neural_network_layer1_output_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_layer2_output_RAM_AUTO_1R1W RTLNAME neural_network_layer2_output_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME neural_network_CONTROL_s_axi RTLNAME neural_network_CONTROL_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME neural_network_INPUT_s_axi RTLNAME neural_network_INPUT_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME neural_network_OUTPUT_s_axi RTLNAME neural_network_OUTPUT_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
