// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module neural_network_neural_network_Pipeline_VITIS_LOOP_84_7_VITIS_LOOP_85_8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer2_weight_tile_address0,
        layer2_weight_tile_ce0,
        layer2_weight_tile_we0,
        layer2_weight_tile_d0,
        zext_ln82,
        layer2_weight_tile_1_address0,
        layer2_weight_tile_1_ce0,
        layer2_weight_tile_1_we0,
        layer2_weight_tile_1_d0,
        layer2_weight_tile_2_address0,
        layer2_weight_tile_2_ce0,
        layer2_weight_tile_2_we0,
        layer2_weight_tile_2_d0,
        layer2_weight_tile_3_address0,
        layer2_weight_tile_3_ce0,
        layer2_weight_tile_3_we0,
        layer2_weight_tile_3_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] layer2_weight_tile_address0;
output   layer2_weight_tile_ce0;
output   layer2_weight_tile_we0;
output  [12:0] layer2_weight_tile_d0;
input  [5:0] zext_ln82;
output  [3:0] layer2_weight_tile_1_address0;
output   layer2_weight_tile_1_ce0;
output   layer2_weight_tile_1_we0;
output  [12:0] layer2_weight_tile_1_d0;
output  [3:0] layer2_weight_tile_2_address0;
output   layer2_weight_tile_2_ce0;
output   layer2_weight_tile_2_we0;
output  [12:0] layer2_weight_tile_2_d0;
output  [3:0] layer2_weight_tile_3_address0;
output   layer2_weight_tile_3_ce0;
output   layer2_weight_tile_3_we0;
output  [12:0] layer2_weight_tile_3_d0;

reg ap_idle;
reg layer2_weight_tile_ce0;
reg layer2_weight_tile_we0;
reg layer2_weight_tile_1_ce0;
reg layer2_weight_tile_1_we0;
reg layer2_weight_tile_2_ce0;
reg layer2_weight_tile_2_we0;
reg layer2_weight_tile_3_ce0;
reg layer2_weight_tile_3_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_subdone;
wire   [0:0] icmp_ln84_fu_167_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] layer2_weights_address0;
reg    layer2_weights_ce0;
wire   [12:0] layer2_weights_q0;
wire   [9:0] zext_ln82_cast_fu_145_p1;
reg   [9:0] zext_ln82_cast_reg_291;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln84_reg_296;
wire    ap_block_pp0_stage1_11001;
wire   [63:0] select_ln84_fu_197_p3;
reg   [63:0] select_ln84_reg_300;
wire   [3:0] select_ln84_1_fu_205_p3;
reg   [3:0] select_ln84_1_reg_305;
wire   [9:0] trunc_ln85_fu_213_p1;
reg   [9:0] trunc_ln85_reg_311;
wire   [1:0] trunc_ln85_1_fu_217_p1;
reg   [1:0] trunc_ln85_1_reg_316;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln87_fu_248_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln84_fu_263_p1;
wire    ap_block_pp0_stage1;
reg   [63:0] j_fu_58;
wire   [63:0] add_ln85_1_fu_253_p2;
wire    ap_loop_init;
reg   [3:0] i_fu_62;
reg   [5:0] indvar_flatten53_fu_66;
wire   [5:0] add_ln84_1_fu_173_p2;
wire   [0:0] icmp_ln85_fu_191_p2;
wire   [3:0] add_ln84_fu_185_p2;
wire   [9:0] tmp_s_fu_231_p3;
wire   [9:0] add_ln85_fu_238_p2;
wire   [9:0] add_ln87_fu_242_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

neural_network_neural_network_Pipeline_VITIS_LOOP_84_7_VITIS_LOOP_85_8_layer2_weights_ROM_AUcud #(
    .DataWidth( 13 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
layer2_weights_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer2_weights_address0),
    .ce0(layer2_weights_ce0),
    .q0(layer2_weights_q0)
);

neural_network_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        i_fu_62 <= 4'd0;
    end else if (((icmp_ln84_fu_167_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_fu_62 <= select_ln84_1_fu_205_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        indvar_flatten53_fu_66 <= 6'd0;
    end else if (((icmp_ln84_fu_167_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indvar_flatten53_fu_66 <= add_ln84_1_fu_173_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_58 <= 64'd0;
        end else if (((icmp_ln84_reg_296 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            j_fu_58 <= add_ln85_1_fu_253_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln84_reg_296 <= icmp_ln84_fu_167_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln84_fu_167_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        select_ln84_1_reg_305 <= select_ln84_1_fu_205_p3;
        select_ln84_reg_300 <= select_ln84_fu_197_p3;
        trunc_ln85_1_reg_316 <= trunc_ln85_1_fu_217_p1;
        trunc_ln85_reg_311 <= trunc_ln85_fu_213_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln82_cast_reg_291[5 : 0] <= zext_ln82_cast_fu_145_p1[5 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln84_fu_167_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer2_weight_tile_1_ce0 = 1'b1;
    end else begin
        layer2_weight_tile_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (trunc_ln85_1_reg_316 == 2'd1))) begin
        layer2_weight_tile_1_we0 = 1'b1;
    end else begin
        layer2_weight_tile_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer2_weight_tile_2_ce0 = 1'b1;
    end else begin
        layer2_weight_tile_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (trunc_ln85_1_reg_316 == 2'd2))) begin
        layer2_weight_tile_2_we0 = 1'b1;
    end else begin
        layer2_weight_tile_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer2_weight_tile_3_ce0 = 1'b1;
    end else begin
        layer2_weight_tile_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (trunc_ln85_1_reg_316 == 2'd3))) begin
        layer2_weight_tile_3_we0 = 1'b1;
    end else begin
        layer2_weight_tile_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer2_weight_tile_ce0 = 1'b1;
    end else begin
        layer2_weight_tile_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (trunc_ln85_1_reg_316 == 2'd0))) begin
        layer2_weight_tile_we0 = 1'b1;
    end else begin
        layer2_weight_tile_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_weights_ce0 = 1'b1;
    end else begin
        layer2_weights_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln84_1_fu_173_p2 = (indvar_flatten53_fu_66 + 6'd1);

assign add_ln84_fu_185_p2 = (i_fu_62 + 4'd1);

assign add_ln85_1_fu_253_p2 = (select_ln84_reg_300 + 64'd1);

assign add_ln85_fu_238_p2 = (trunc_ln85_reg_311 + zext_ln82_cast_reg_291);

assign add_ln87_fu_242_p2 = (tmp_s_fu_231_p3 + add_ln85_fu_238_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign icmp_ln84_fu_167_p2 = ((indvar_flatten53_fu_66 == 6'd40) ? 1'b1 : 1'b0);

assign icmp_ln85_fu_191_p2 = ((j_fu_58 == 64'd4) ? 1'b1 : 1'b0);

assign layer2_weight_tile_1_address0 = zext_ln84_fu_263_p1;

assign layer2_weight_tile_1_d0 = layer2_weights_q0;

assign layer2_weight_tile_2_address0 = zext_ln84_fu_263_p1;

assign layer2_weight_tile_2_d0 = layer2_weights_q0;

assign layer2_weight_tile_3_address0 = zext_ln84_fu_263_p1;

assign layer2_weight_tile_3_d0 = layer2_weights_q0;

assign layer2_weight_tile_address0 = zext_ln84_fu_263_p1;

assign layer2_weight_tile_d0 = layer2_weights_q0;

assign layer2_weights_address0 = zext_ln87_fu_248_p1;

assign select_ln84_1_fu_205_p3 = ((icmp_ln85_fu_191_p2[0:0] == 1'b1) ? add_ln84_fu_185_p2 : i_fu_62);

assign select_ln84_fu_197_p3 = ((icmp_ln85_fu_191_p2[0:0] == 1'b1) ? 64'd0 : j_fu_58);

assign tmp_s_fu_231_p3 = {{select_ln84_1_reg_305}, {6'd0}};

assign trunc_ln85_1_fu_217_p1 = select_ln84_fu_197_p3[1:0];

assign trunc_ln85_fu_213_p1 = select_ln84_fu_197_p3[9:0];

assign zext_ln82_cast_fu_145_p1 = zext_ln82;

assign zext_ln84_fu_263_p1 = select_ln84_1_reg_305;

assign zext_ln87_fu_248_p1 = add_ln87_fu_242_p2;

always @ (posedge ap_clk) begin
    zext_ln82_cast_reg_291[9:6] <= 4'b0000;
end

endmodule //neural_network_neural_network_Pipeline_VITIS_LOOP_84_7_VITIS_LOOP_85_8
